/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateCourseDto,
  GetCourseDto,
  UpdateCourseDto,
} from '.././model';

export type courseControllerCreateCourseResponse201 = {
  data: GetCourseDto;
  status: 201;
};

export type courseControllerCreateCourseResponseSuccess =
  courseControllerCreateCourseResponse201 & {
    headers: Headers;
  };
export type courseControllerCreateCourseResponse =
  courseControllerCreateCourseResponseSuccess;

export const getCourseControllerCreateCourseUrl = () => {
  return `/api/v1/courses`;
};

export const courseControllerCreateCourse = async (
  createCourseDto: CreateCourseDto,
  options?: RequestInit
): Promise<courseControllerCreateCourseResponse> => {
  const res = await fetch(getCourseControllerCreateCourseUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCourseDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: courseControllerCreateCourseResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as courseControllerCreateCourseResponse;
};

export const getCourseControllerCreateCourseMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof courseControllerCreateCourse>>,
    TError,
    { data: CreateCourseDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof courseControllerCreateCourse>>,
  TError,
  { data: CreateCourseDto },
  TContext
> => {
  const mutationKey = ['courseControllerCreateCourse'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof courseControllerCreateCourse>>,
    { data: CreateCourseDto }
  > = (props) => {
    const { data } = props ?? {};

    return courseControllerCreateCourse(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CourseControllerCreateCourseMutationResult = NonNullable<
  Awaited<ReturnType<typeof courseControllerCreateCourse>>
>;
export type CourseControllerCreateCourseMutationBody = CreateCourseDto;
export type CourseControllerCreateCourseMutationError = unknown;

export const useCourseControllerCreateCourse = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof courseControllerCreateCourse>>,
      TError,
      { data: CreateCourseDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof courseControllerCreateCourse>>,
  TError,
  { data: CreateCourseDto },
  TContext
> => {
  return useMutation(
    getCourseControllerCreateCourseMutationOptions(options),
    queryClient
  );
};
export type courseControllerGetAllCoursesResponse200 = {
  data: GetCourseDto[];
  status: 200;
};

export type courseControllerGetAllCoursesResponseSuccess =
  courseControllerGetAllCoursesResponse200 & {
    headers: Headers;
  };
export type courseControllerGetAllCoursesResponse =
  courseControllerGetAllCoursesResponseSuccess;

export const getCourseControllerGetAllCoursesUrl = () => {
  return `/api/v1/courses`;
};

export const courseControllerGetAllCourses = async (
  options?: RequestInit
): Promise<courseControllerGetAllCoursesResponse> => {
  const res = await fetch(getCourseControllerGetAllCoursesUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: courseControllerGetAllCoursesResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as courseControllerGetAllCoursesResponse;
};

export const getCourseControllerGetAllCoursesQueryKey = () => {
  return [`/api/v1/courses`] as const;
};

export const getCourseControllerGetAllCoursesQueryOptions = <
  TData = Awaited<ReturnType<typeof courseControllerGetAllCourses>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof courseControllerGetAllCourses>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCourseControllerGetAllCoursesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof courseControllerGetAllCourses>>
  > = ({ signal }) =>
    courseControllerGetAllCourses({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof courseControllerGetAllCourses>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CourseControllerGetAllCoursesQueryResult = NonNullable<
  Awaited<ReturnType<typeof courseControllerGetAllCourses>>
>;
export type CourseControllerGetAllCoursesQueryError = unknown;

export function useCourseControllerGetAllCourses<
  TData = Awaited<ReturnType<typeof courseControllerGetAllCourses>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof courseControllerGetAllCourses>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof courseControllerGetAllCourses>>,
          TError,
          Awaited<ReturnType<typeof courseControllerGetAllCourses>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCourseControllerGetAllCourses<
  TData = Awaited<ReturnType<typeof courseControllerGetAllCourses>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof courseControllerGetAllCourses>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof courseControllerGetAllCourses>>,
          TError,
          Awaited<ReturnType<typeof courseControllerGetAllCourses>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCourseControllerGetAllCourses<
  TData = Awaited<ReturnType<typeof courseControllerGetAllCourses>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof courseControllerGetAllCourses>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCourseControllerGetAllCourses<
  TData = Awaited<ReturnType<typeof courseControllerGetAllCourses>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof courseControllerGetAllCourses>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCourseControllerGetAllCoursesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type courseControllerGetCourseByIdResponse200 = {
  data: GetCourseDto;
  status: 200;
};

export type courseControllerGetCourseByIdResponseSuccess =
  courseControllerGetCourseByIdResponse200 & {
    headers: Headers;
  };
export type courseControllerGetCourseByIdResponse =
  courseControllerGetCourseByIdResponseSuccess;

export const getCourseControllerGetCourseByIdUrl = (id: string) => {
  return `/api/v1/courses/${id}`;
};

export const courseControllerGetCourseById = async (
  id: string,
  options?: RequestInit
): Promise<courseControllerGetCourseByIdResponse> => {
  const res = await fetch(getCourseControllerGetCourseByIdUrl(id), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: courseControllerGetCourseByIdResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as courseControllerGetCourseByIdResponse;
};

export const getCourseControllerGetCourseByIdQueryKey = (id: string) => {
  return [`/api/v1/courses/${id}`] as const;
};

export const getCourseControllerGetCourseByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof courseControllerGetCourseById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof courseControllerGetCourseById>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  }
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCourseControllerGetCourseByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof courseControllerGetCourseById>>
  > = ({ signal }) =>
    courseControllerGetCourseById(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof courseControllerGetCourseById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CourseControllerGetCourseByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof courseControllerGetCourseById>>
>;
export type CourseControllerGetCourseByIdQueryError = unknown;

export function useCourseControllerGetCourseById<
  TData = Awaited<ReturnType<typeof courseControllerGetCourseById>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof courseControllerGetCourseById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof courseControllerGetCourseById>>,
          TError,
          Awaited<ReturnType<typeof courseControllerGetCourseById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCourseControllerGetCourseById<
  TData = Awaited<ReturnType<typeof courseControllerGetCourseById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof courseControllerGetCourseById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof courseControllerGetCourseById>>,
          TError,
          Awaited<ReturnType<typeof courseControllerGetCourseById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCourseControllerGetCourseById<
  TData = Awaited<ReturnType<typeof courseControllerGetCourseById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof courseControllerGetCourseById>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCourseControllerGetCourseById<
  TData = Awaited<ReturnType<typeof courseControllerGetCourseById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof courseControllerGetCourseById>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCourseControllerGetCourseByIdQueryOptions(
    id,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type courseControllerUpdateCourseResponse200 = {
  data: GetCourseDto;
  status: 200;
};

export type courseControllerUpdateCourseResponseSuccess =
  courseControllerUpdateCourseResponse200 & {
    headers: Headers;
  };
export type courseControllerUpdateCourseResponse =
  courseControllerUpdateCourseResponseSuccess;

export const getCourseControllerUpdateCourseUrl = (id: string) => {
  return `/api/v1/courses/${id}`;
};

export const courseControllerUpdateCourse = async (
  id: string,
  updateCourseDto: UpdateCourseDto,
  options?: RequestInit
): Promise<courseControllerUpdateCourseResponse> => {
  const res = await fetch(getCourseControllerUpdateCourseUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateCourseDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: courseControllerUpdateCourseResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as courseControllerUpdateCourseResponse;
};

export const getCourseControllerUpdateCourseMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof courseControllerUpdateCourse>>,
    TError,
    { id: string; data: UpdateCourseDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof courseControllerUpdateCourse>>,
  TError,
  { id: string; data: UpdateCourseDto },
  TContext
> => {
  const mutationKey = ['courseControllerUpdateCourse'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof courseControllerUpdateCourse>>,
    { id: string; data: UpdateCourseDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return courseControllerUpdateCourse(id, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CourseControllerUpdateCourseMutationResult = NonNullable<
  Awaited<ReturnType<typeof courseControllerUpdateCourse>>
>;
export type CourseControllerUpdateCourseMutationBody = UpdateCourseDto;
export type CourseControllerUpdateCourseMutationError = unknown;

export const useCourseControllerUpdateCourse = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof courseControllerUpdateCourse>>,
      TError,
      { id: string; data: UpdateCourseDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof courseControllerUpdateCourse>>,
  TError,
  { id: string; data: UpdateCourseDto },
  TContext
> => {
  return useMutation(
    getCourseControllerUpdateCourseMutationOptions(options),
    queryClient
  );
};
export type courseControllerDeleteCourseByIdResponse200 = {
  data: void;
  status: 200;
};

export type courseControllerDeleteCourseByIdResponseSuccess =
  courseControllerDeleteCourseByIdResponse200 & {
    headers: Headers;
  };
export type courseControllerDeleteCourseByIdResponse =
  courseControllerDeleteCourseByIdResponseSuccess;

export const getCourseControllerDeleteCourseByIdUrl = (id: string) => {
  return `/api/v1/courses/${id}`;
};

export const courseControllerDeleteCourseById = async (
  id: string,
  options?: RequestInit
): Promise<courseControllerDeleteCourseByIdResponse> => {
  const res = await fetch(getCourseControllerDeleteCourseByIdUrl(id), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: courseControllerDeleteCourseByIdResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as courseControllerDeleteCourseByIdResponse;
};

export const getCourseControllerDeleteCourseByIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof courseControllerDeleteCourseById>>,
    TError,
    { id: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof courseControllerDeleteCourseById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['courseControllerDeleteCourseById'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof courseControllerDeleteCourseById>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return courseControllerDeleteCourseById(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CourseControllerDeleteCourseByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof courseControllerDeleteCourseById>>
>;

export type CourseControllerDeleteCourseByIdMutationError = unknown;

export const useCourseControllerDeleteCourseById = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof courseControllerDeleteCourseById>>,
      TError,
      { id: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof courseControllerDeleteCourseById>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getCourseControllerDeleteCourseByIdMutationOptions(options),
    queryClient
  );
};
