/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateLocationDto,
  GetLocationDto,
  UpdateLocationDto,
} from '.././model';

export type locationControllerCreateLocationResponse201 = {
  data: GetLocationDto;
  status: 201;
};

export type locationControllerCreateLocationResponseSuccess =
  locationControllerCreateLocationResponse201 & {
    headers: Headers;
  };
export type locationControllerCreateLocationResponse =
  locationControllerCreateLocationResponseSuccess;

export const getLocationControllerCreateLocationUrl = () => {
  return `/api/v1/locations`;
};

export const locationControllerCreateLocation = async (
  createLocationDto: CreateLocationDto,
  options?: RequestInit
): Promise<locationControllerCreateLocationResponse> => {
  const res = await fetch(getLocationControllerCreateLocationUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createLocationDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: locationControllerCreateLocationResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as locationControllerCreateLocationResponse;
};

export const getLocationControllerCreateLocationMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof locationControllerCreateLocation>>,
    TError,
    { data: CreateLocationDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof locationControllerCreateLocation>>,
  TError,
  { data: CreateLocationDto },
  TContext
> => {
  const mutationKey = ['locationControllerCreateLocation'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof locationControllerCreateLocation>>,
    { data: CreateLocationDto }
  > = (props) => {
    const { data } = props ?? {};

    return locationControllerCreateLocation(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LocationControllerCreateLocationMutationResult = NonNullable<
  Awaited<ReturnType<typeof locationControllerCreateLocation>>
>;
export type LocationControllerCreateLocationMutationBody = CreateLocationDto;
export type LocationControllerCreateLocationMutationError = unknown;

export const useLocationControllerCreateLocation = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof locationControllerCreateLocation>>,
      TError,
      { data: CreateLocationDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof locationControllerCreateLocation>>,
  TError,
  { data: CreateLocationDto },
  TContext
> => {
  return useMutation(
    getLocationControllerCreateLocationMutationOptions(options),
    queryClient
  );
};
export type locationControllerGetAllLocationsResponse200 = {
  data: GetLocationDto[];
  status: 200;
};

export type locationControllerGetAllLocationsResponseSuccess =
  locationControllerGetAllLocationsResponse200 & {
    headers: Headers;
  };
export type locationControllerGetAllLocationsResponse =
  locationControllerGetAllLocationsResponseSuccess;

export const getLocationControllerGetAllLocationsUrl = () => {
  return `/api/v1/locations`;
};

export const locationControllerGetAllLocations = async (
  options?: RequestInit
): Promise<locationControllerGetAllLocationsResponse> => {
  const res = await fetch(getLocationControllerGetAllLocationsUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: locationControllerGetAllLocationsResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as locationControllerGetAllLocationsResponse;
};

export const getLocationControllerGetAllLocationsQueryKey = () => {
  return [`/api/v1/locations`] as const;
};

export const getLocationControllerGetAllLocationsQueryOptions = <
  TData = Awaited<ReturnType<typeof locationControllerGetAllLocations>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof locationControllerGetAllLocations>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getLocationControllerGetAllLocationsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof locationControllerGetAllLocations>>
  > = ({ signal }) =>
    locationControllerGetAllLocations({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof locationControllerGetAllLocations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type LocationControllerGetAllLocationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof locationControllerGetAllLocations>>
>;
export type LocationControllerGetAllLocationsQueryError = unknown;

export function useLocationControllerGetAllLocations<
  TData = Awaited<ReturnType<typeof locationControllerGetAllLocations>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof locationControllerGetAllLocations>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof locationControllerGetAllLocations>>,
          TError,
          Awaited<ReturnType<typeof locationControllerGetAllLocations>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLocationControllerGetAllLocations<
  TData = Awaited<ReturnType<typeof locationControllerGetAllLocations>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof locationControllerGetAllLocations>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof locationControllerGetAllLocations>>,
          TError,
          Awaited<ReturnType<typeof locationControllerGetAllLocations>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLocationControllerGetAllLocations<
  TData = Awaited<ReturnType<typeof locationControllerGetAllLocations>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof locationControllerGetAllLocations>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useLocationControllerGetAllLocations<
  TData = Awaited<ReturnType<typeof locationControllerGetAllLocations>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof locationControllerGetAllLocations>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getLocationControllerGetAllLocationsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type locationControllerGetLocationByIdResponse200 = {
  data: GetLocationDto;
  status: 200;
};

export type locationControllerGetLocationByIdResponseSuccess =
  locationControllerGetLocationByIdResponse200 & {
    headers: Headers;
  };
export type locationControllerGetLocationByIdResponse =
  locationControllerGetLocationByIdResponseSuccess;

export const getLocationControllerGetLocationByIdUrl = (id: string) => {
  return `/api/v1/locations/${id}`;
};

export const locationControllerGetLocationById = async (
  id: string,
  options?: RequestInit
): Promise<locationControllerGetLocationByIdResponse> => {
  const res = await fetch(getLocationControllerGetLocationByIdUrl(id), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: locationControllerGetLocationByIdResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as locationControllerGetLocationByIdResponse;
};

export const getLocationControllerGetLocationByIdQueryKey = (id: string) => {
  return [`/api/v1/locations/${id}`] as const;
};

export const getLocationControllerGetLocationByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof locationControllerGetLocationById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof locationControllerGetLocationById>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  }
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getLocationControllerGetLocationByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof locationControllerGetLocationById>>
  > = ({ signal }) =>
    locationControllerGetLocationById(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof locationControllerGetLocationById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type LocationControllerGetLocationByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof locationControllerGetLocationById>>
>;
export type LocationControllerGetLocationByIdQueryError = unknown;

export function useLocationControllerGetLocationById<
  TData = Awaited<ReturnType<typeof locationControllerGetLocationById>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof locationControllerGetLocationById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof locationControllerGetLocationById>>,
          TError,
          Awaited<ReturnType<typeof locationControllerGetLocationById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLocationControllerGetLocationById<
  TData = Awaited<ReturnType<typeof locationControllerGetLocationById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof locationControllerGetLocationById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof locationControllerGetLocationById>>,
          TError,
          Awaited<ReturnType<typeof locationControllerGetLocationById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useLocationControllerGetLocationById<
  TData = Awaited<ReturnType<typeof locationControllerGetLocationById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof locationControllerGetLocationById>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useLocationControllerGetLocationById<
  TData = Awaited<ReturnType<typeof locationControllerGetLocationById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof locationControllerGetLocationById>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getLocationControllerGetLocationByIdQueryOptions(
    id,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type locationControllerUpdateLocationResponse200 = {
  data: GetLocationDto;
  status: 200;
};

export type locationControllerUpdateLocationResponseSuccess =
  locationControllerUpdateLocationResponse200 & {
    headers: Headers;
  };
export type locationControllerUpdateLocationResponse =
  locationControllerUpdateLocationResponseSuccess;

export const getLocationControllerUpdateLocationUrl = (id: string) => {
  return `/api/v1/locations/${id}`;
};

export const locationControllerUpdateLocation = async (
  id: string,
  updateLocationDto: UpdateLocationDto,
  options?: RequestInit
): Promise<locationControllerUpdateLocationResponse> => {
  const res = await fetch(getLocationControllerUpdateLocationUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateLocationDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: locationControllerUpdateLocationResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as locationControllerUpdateLocationResponse;
};

export const getLocationControllerUpdateLocationMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof locationControllerUpdateLocation>>,
    TError,
    { id: string; data: UpdateLocationDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof locationControllerUpdateLocation>>,
  TError,
  { id: string; data: UpdateLocationDto },
  TContext
> => {
  const mutationKey = ['locationControllerUpdateLocation'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof locationControllerUpdateLocation>>,
    { id: string; data: UpdateLocationDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return locationControllerUpdateLocation(id, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LocationControllerUpdateLocationMutationResult = NonNullable<
  Awaited<ReturnType<typeof locationControllerUpdateLocation>>
>;
export type LocationControllerUpdateLocationMutationBody = UpdateLocationDto;
export type LocationControllerUpdateLocationMutationError = unknown;

export const useLocationControllerUpdateLocation = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof locationControllerUpdateLocation>>,
      TError,
      { id: string; data: UpdateLocationDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof locationControllerUpdateLocation>>,
  TError,
  { id: string; data: UpdateLocationDto },
  TContext
> => {
  return useMutation(
    getLocationControllerUpdateLocationMutationOptions(options),
    queryClient
  );
};
export type locationControllerDeleteLocationByIdResponse200 = {
  data: void;
  status: 200;
};

export type locationControllerDeleteLocationByIdResponseSuccess =
  locationControllerDeleteLocationByIdResponse200 & {
    headers: Headers;
  };
export type locationControllerDeleteLocationByIdResponse =
  locationControllerDeleteLocationByIdResponseSuccess;

export const getLocationControllerDeleteLocationByIdUrl = (id: string) => {
  return `/api/v1/locations/${id}`;
};

export const locationControllerDeleteLocationById = async (
  id: string,
  options?: RequestInit
): Promise<locationControllerDeleteLocationByIdResponse> => {
  const res = await fetch(getLocationControllerDeleteLocationByIdUrl(id), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: locationControllerDeleteLocationByIdResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as locationControllerDeleteLocationByIdResponse;
};

export const getLocationControllerDeleteLocationByIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof locationControllerDeleteLocationById>>,
    TError,
    { id: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof locationControllerDeleteLocationById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['locationControllerDeleteLocationById'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof locationControllerDeleteLocationById>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return locationControllerDeleteLocationById(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LocationControllerDeleteLocationByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof locationControllerDeleteLocationById>>
>;

export type LocationControllerDeleteLocationByIdMutationError = unknown;

export const useLocationControllerDeleteLocationById = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof locationControllerDeleteLocationById>>,
      TError,
      { id: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof locationControllerDeleteLocationById>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getLocationControllerDeleteLocationByIdMutationOptions(options),
    queryClient
  );
};
