/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */

export interface CreateAddressDto {
  street: string;
  houseNumber: number;
  zipCode: number;
  city: string;
  country: string;
}
