/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */
import type { GetAddressDto } from './getAddressDto';

export interface GetLocationDto {
  id: string;
  name: string;
  address: GetAddressDto;
}
