/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */
import type { HealthControllerReady200Details } from './healthControllerReady200Details';
import type { HealthControllerReady200Error } from './healthControllerReady200Error';
import type { HealthControllerReady200Info } from './healthControllerReady200Info';

export type HealthControllerReady200 = {
  status?: string;
  /** @nullable */
  info?: HealthControllerReady200Info;
  /** @nullable */
  error?: HealthControllerReady200Error;
  details?: HealthControllerReady200Details;
};
