/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */
import type { HealthControllerDetails200Details } from './healthControllerDetails200Details';
import type { HealthControllerDetails200Error } from './healthControllerDetails200Error';
import type { HealthControllerDetails200Info } from './healthControllerDetails200Info';

export type HealthControllerDetails200 = {
  status?: string;
  /** @nullable */
  info?: HealthControllerDetails200Info;
  /** @nullable */
  error?: HealthControllerDetails200Error;
  details?: HealthControllerDetails200Details;
};
