/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type HealthControllerReady200Error = {
  [key: string]: {
    status: string;
    [key: string]: unknown;
  };
} | null;
