/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */

export interface UpdateCourseDto {
  name?: string;
  abbreviation?: string;
}
