/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { CreateRankDto, GetRankDto, UpdateRankDto } from '.././model';

export type rankControllerCreateRankResponse201 = {
  data: GetRankDto;
  status: 201;
};

export type rankControllerCreateRankResponseSuccess =
  rankControllerCreateRankResponse201 & {
    headers: Headers;
  };
export type rankControllerCreateRankResponse =
  rankControllerCreateRankResponseSuccess;

export const getRankControllerCreateRankUrl = () => {
  return `/api/v1/ranks`;
};

export const rankControllerCreateRank = async (
  createRankDto: CreateRankDto,
  options?: RequestInit
): Promise<rankControllerCreateRankResponse> => {
  const res = await fetch(getRankControllerCreateRankUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createRankDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rankControllerCreateRankResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as rankControllerCreateRankResponse;
};

export const getRankControllerCreateRankMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof rankControllerCreateRank>>,
    TError,
    { data: CreateRankDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof rankControllerCreateRank>>,
  TError,
  { data: CreateRankDto },
  TContext
> => {
  const mutationKey = ['rankControllerCreateRank'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof rankControllerCreateRank>>,
    { data: CreateRankDto }
  > = (props) => {
    const { data } = props ?? {};

    return rankControllerCreateRank(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RankControllerCreateRankMutationResult = NonNullable<
  Awaited<ReturnType<typeof rankControllerCreateRank>>
>;
export type RankControllerCreateRankMutationBody = CreateRankDto;
export type RankControllerCreateRankMutationError = unknown;

export const useRankControllerCreateRank = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof rankControllerCreateRank>>,
      TError,
      { data: CreateRankDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof rankControllerCreateRank>>,
  TError,
  { data: CreateRankDto },
  TContext
> => {
  return useMutation(
    getRankControllerCreateRankMutationOptions(options),
    queryClient
  );
};
export type rankControllerGetAllRanksResponse200 = {
  data: GetRankDto[];
  status: 200;
};

export type rankControllerGetAllRanksResponseSuccess =
  rankControllerGetAllRanksResponse200 & {
    headers: Headers;
  };
export type rankControllerGetAllRanksResponse =
  rankControllerGetAllRanksResponseSuccess;

export const getRankControllerGetAllRanksUrl = () => {
  return `/api/v1/ranks`;
};

export const rankControllerGetAllRanks = async (
  options?: RequestInit
): Promise<rankControllerGetAllRanksResponse> => {
  const res = await fetch(getRankControllerGetAllRanksUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rankControllerGetAllRanksResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as rankControllerGetAllRanksResponse;
};

export const getRankControllerGetAllRanksQueryKey = () => {
  return [`/api/v1/ranks`] as const;
};

export const getRankControllerGetAllRanksQueryOptions = <
  TData = Awaited<ReturnType<typeof rankControllerGetAllRanks>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof rankControllerGetAllRanks>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getRankControllerGetAllRanksQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof rankControllerGetAllRanks>>
  > = ({ signal }) => rankControllerGetAllRanks({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof rankControllerGetAllRanks>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RankControllerGetAllRanksQueryResult = NonNullable<
  Awaited<ReturnType<typeof rankControllerGetAllRanks>>
>;
export type RankControllerGetAllRanksQueryError = unknown;

export function useRankControllerGetAllRanks<
  TData = Awaited<ReturnType<typeof rankControllerGetAllRanks>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof rankControllerGetAllRanks>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rankControllerGetAllRanks>>,
          TError,
          Awaited<ReturnType<typeof rankControllerGetAllRanks>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRankControllerGetAllRanks<
  TData = Awaited<ReturnType<typeof rankControllerGetAllRanks>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof rankControllerGetAllRanks>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rankControllerGetAllRanks>>,
          TError,
          Awaited<ReturnType<typeof rankControllerGetAllRanks>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRankControllerGetAllRanks<
  TData = Awaited<ReturnType<typeof rankControllerGetAllRanks>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof rankControllerGetAllRanks>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useRankControllerGetAllRanks<
  TData = Awaited<ReturnType<typeof rankControllerGetAllRanks>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof rankControllerGetAllRanks>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getRankControllerGetAllRanksQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type rankControllerGetRankByIdResponse200 = {
  data: GetRankDto;
  status: 200;
};

export type rankControllerGetRankByIdResponseSuccess =
  rankControllerGetRankByIdResponse200 & {
    headers: Headers;
  };
export type rankControllerGetRankByIdResponse =
  rankControllerGetRankByIdResponseSuccess;

export const getRankControllerGetRankByIdUrl = (id: string) => {
  return `/api/v1/ranks/${id}`;
};

export const rankControllerGetRankById = async (
  id: string,
  options?: RequestInit
): Promise<rankControllerGetRankByIdResponse> => {
  const res = await fetch(getRankControllerGetRankByIdUrl(id), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rankControllerGetRankByIdResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as rankControllerGetRankByIdResponse;
};

export const getRankControllerGetRankByIdQueryKey = (id: string) => {
  return [`/api/v1/ranks/${id}`] as const;
};

export const getRankControllerGetRankByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof rankControllerGetRankById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof rankControllerGetRankById>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  }
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getRankControllerGetRankByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof rankControllerGetRankById>>
  > = ({ signal }) =>
    rankControllerGetRankById(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof rankControllerGetRankById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RankControllerGetRankByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof rankControllerGetRankById>>
>;
export type RankControllerGetRankByIdQueryError = unknown;

export function useRankControllerGetRankById<
  TData = Awaited<ReturnType<typeof rankControllerGetRankById>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof rankControllerGetRankById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rankControllerGetRankById>>,
          TError,
          Awaited<ReturnType<typeof rankControllerGetRankById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRankControllerGetRankById<
  TData = Awaited<ReturnType<typeof rankControllerGetRankById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof rankControllerGetRankById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rankControllerGetRankById>>,
          TError,
          Awaited<ReturnType<typeof rankControllerGetRankById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRankControllerGetRankById<
  TData = Awaited<ReturnType<typeof rankControllerGetRankById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof rankControllerGetRankById>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useRankControllerGetRankById<
  TData = Awaited<ReturnType<typeof rankControllerGetRankById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof rankControllerGetRankById>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getRankControllerGetRankByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type rankControllerUpdateRankResponse200 = {
  data: GetRankDto;
  status: 200;
};

export type rankControllerUpdateRankResponseSuccess =
  rankControllerUpdateRankResponse200 & {
    headers: Headers;
  };
export type rankControllerUpdateRankResponse =
  rankControllerUpdateRankResponseSuccess;

export const getRankControllerUpdateRankUrl = (id: string) => {
  return `/api/v1/ranks/${id}`;
};

export const rankControllerUpdateRank = async (
  id: string,
  updateRankDto: UpdateRankDto,
  options?: RequestInit
): Promise<rankControllerUpdateRankResponse> => {
  const res = await fetch(getRankControllerUpdateRankUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateRankDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rankControllerUpdateRankResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as rankControllerUpdateRankResponse;
};

export const getRankControllerUpdateRankMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof rankControllerUpdateRank>>,
    TError,
    { id: string; data: UpdateRankDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof rankControllerUpdateRank>>,
  TError,
  { id: string; data: UpdateRankDto },
  TContext
> => {
  const mutationKey = ['rankControllerUpdateRank'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof rankControllerUpdateRank>>,
    { id: string; data: UpdateRankDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return rankControllerUpdateRank(id, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RankControllerUpdateRankMutationResult = NonNullable<
  Awaited<ReturnType<typeof rankControllerUpdateRank>>
>;
export type RankControllerUpdateRankMutationBody = UpdateRankDto;
export type RankControllerUpdateRankMutationError = unknown;

export const useRankControllerUpdateRank = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof rankControllerUpdateRank>>,
      TError,
      { id: string; data: UpdateRankDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof rankControllerUpdateRank>>,
  TError,
  { id: string; data: UpdateRankDto },
  TContext
> => {
  return useMutation(
    getRankControllerUpdateRankMutationOptions(options),
    queryClient
  );
};
export type rankControllerDeleteRankByIdResponse200 = {
  data: void;
  status: 200;
};

export type rankControllerDeleteRankByIdResponseSuccess =
  rankControllerDeleteRankByIdResponse200 & {
    headers: Headers;
  };
export type rankControllerDeleteRankByIdResponse =
  rankControllerDeleteRankByIdResponseSuccess;

export const getRankControllerDeleteRankByIdUrl = (id: string) => {
  return `/api/v1/ranks/${id}`;
};

export const rankControllerDeleteRankById = async (
  id: string,
  options?: RequestInit
): Promise<rankControllerDeleteRankByIdResponse> => {
  const res = await fetch(getRankControllerDeleteRankByIdUrl(id), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rankControllerDeleteRankByIdResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as rankControllerDeleteRankByIdResponse;
};

export const getRankControllerDeleteRankByIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof rankControllerDeleteRankById>>,
    TError,
    { id: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof rankControllerDeleteRankById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['rankControllerDeleteRankById'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof rankControllerDeleteRankById>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return rankControllerDeleteRankById(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RankControllerDeleteRankByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof rankControllerDeleteRankById>>
>;

export type RankControllerDeleteRankByIdMutationError = unknown;

export const useRankControllerDeleteRankById = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof rankControllerDeleteRankById>>,
      TError,
      { id: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof rankControllerDeleteRankById>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getRankControllerDeleteRankByIdMutationOptions(options),
    queryClient
  );
};
