/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { CreateUserDto, GetUserDto, UpdateUserDto } from '.././model';

export type userControllerCreateUserResponse201 = {
  data: GetUserDto;
  status: 201;
};

export type userControllerCreateUserResponseSuccess =
  userControllerCreateUserResponse201 & {
    headers: Headers;
  };
export type userControllerCreateUserResponse =
  userControllerCreateUserResponseSuccess;

export const getUserControllerCreateUserUrl = () => {
  return `/api/v1/users`;
};

export const userControllerCreateUser = async (
  createUserDto: CreateUserDto,
  options?: RequestInit
): Promise<userControllerCreateUserResponse> => {
  const res = await fetch(getUserControllerCreateUserUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createUserDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: userControllerCreateUserResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as userControllerCreateUserResponse;
};

export const getUserControllerCreateUserMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerCreateUser>>,
    TError,
    { data: CreateUserDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerCreateUser>>,
  TError,
  { data: CreateUserDto },
  TContext
> => {
  const mutationKey = ['userControllerCreateUser'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerCreateUser>>,
    { data: CreateUserDto }
  > = (props) => {
    const { data } = props ?? {};

    return userControllerCreateUser(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerCreateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerCreateUser>>
>;
export type UserControllerCreateUserMutationBody = CreateUserDto;
export type UserControllerCreateUserMutationError = unknown;

export const useUserControllerCreateUser = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerCreateUser>>,
      TError,
      { data: CreateUserDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerCreateUser>>,
  TError,
  { data: CreateUserDto },
  TContext
> => {
  return useMutation(
    getUserControllerCreateUserMutationOptions(options),
    queryClient
  );
};
export type userControllerGetUserByIdResponse200 = {
  data: GetUserDto;
  status: 200;
};

export type userControllerGetUserByIdResponseSuccess =
  userControllerGetUserByIdResponse200 & {
    headers: Headers;
  };
export type userControllerGetUserByIdResponse =
  userControllerGetUserByIdResponseSuccess;

export const getUserControllerGetUserByIdUrl = (id: string) => {
  return `/api/v1/users/${id}`;
};

export const userControllerGetUserById = async (
  id: string,
  options?: RequestInit
): Promise<userControllerGetUserByIdResponse> => {
  const res = await fetch(getUserControllerGetUserByIdUrl(id), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: userControllerGetUserByIdResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as userControllerGetUserByIdResponse;
};

export const getUserControllerGetUserByIdQueryKey = (id: string) => {
  return [`/api/v1/users/${id}`] as const;
};

export const getUserControllerGetUserByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerGetUserById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof userControllerGetUserById>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  }
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUserControllerGetUserByIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof userControllerGetUserById>>
  > = ({ signal }) =>
    userControllerGetUserById(id, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerGetUserById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserControllerGetUserByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetUserById>>
>;
export type UserControllerGetUserByIdQueryError = unknown;

export function useUserControllerGetUserById<
  TData = Awaited<ReturnType<typeof userControllerGetUserById>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof userControllerGetUserById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetUserById>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetUserById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUserControllerGetUserById<
  TData = Awaited<ReturnType<typeof userControllerGetUserById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof userControllerGetUserById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetUserById>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetUserById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUserControllerGetUserById<
  TData = Awaited<ReturnType<typeof userControllerGetUserById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof userControllerGetUserById>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUserControllerGetUserById<
  TData = Awaited<ReturnType<typeof userControllerGetUserById>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof userControllerGetUserById>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUserControllerGetUserByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type userControllerUpdateUserResponse200 = {
  data: GetUserDto;
  status: 200;
};

export type userControllerUpdateUserResponseSuccess =
  userControllerUpdateUserResponse200 & {
    headers: Headers;
  };
export type userControllerUpdateUserResponse =
  userControllerUpdateUserResponseSuccess;

export const getUserControllerUpdateUserUrl = (id: string) => {
  return `/api/v1/users/${id}`;
};

export const userControllerUpdateUser = async (
  id: string,
  updateUserDto: UpdateUserDto,
  options?: RequestInit
): Promise<userControllerUpdateUserResponse> => {
  const res = await fetch(getUserControllerUpdateUserUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateUserDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: userControllerUpdateUserResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as userControllerUpdateUserResponse;
};

export const getUserControllerUpdateUserMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerUpdateUser>>,
    TError,
    { id: string; data: UpdateUserDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerUpdateUser>>,
  TError,
  { id: string; data: UpdateUserDto },
  TContext
> => {
  const mutationKey = ['userControllerUpdateUser'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerUpdateUser>>,
    { id: string; data: UpdateUserDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return userControllerUpdateUser(id, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerUpdateUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerUpdateUser>>
>;
export type UserControllerUpdateUserMutationBody = UpdateUserDto;
export type UserControllerUpdateUserMutationError = unknown;

export const useUserControllerUpdateUser = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerUpdateUser>>,
      TError,
      { id: string; data: UpdateUserDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerUpdateUser>>,
  TError,
  { id: string; data: UpdateUserDto },
  TContext
> => {
  return useMutation(
    getUserControllerUpdateUserMutationOptions(options),
    queryClient
  );
};
export type userControllerDeleteUserByIdResponse200 = {
  data: void;
  status: 200;
};

export type userControllerDeleteUserByIdResponseSuccess =
  userControllerDeleteUserByIdResponse200 & {
    headers: Headers;
  };
export type userControllerDeleteUserByIdResponse =
  userControllerDeleteUserByIdResponseSuccess;

export const getUserControllerDeleteUserByIdUrl = (id: string) => {
  return `/api/v1/users/${id}`;
};

export const userControllerDeleteUserById = async (
  id: string,
  options?: RequestInit
): Promise<userControllerDeleteUserByIdResponse> => {
  const res = await fetch(getUserControllerDeleteUserByIdUrl(id), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: userControllerDeleteUserByIdResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as userControllerDeleteUserByIdResponse;
};

export const getUserControllerDeleteUserByIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerDeleteUserById>>,
    TError,
    { id: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerDeleteUserById>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['userControllerDeleteUserById'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerDeleteUserById>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return userControllerDeleteUserById(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerDeleteUserByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerDeleteUserById>>
>;

export type UserControllerDeleteUserByIdMutationError = unknown;

export const useUserControllerDeleteUserById = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerDeleteUserById>>,
      TError,
      { id: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerDeleteUserById>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getUserControllerDeleteUserByIdMutationOptions(options),
    queryClient
  );
};
export type userControllerGetProfileResponse200 = {
  data: void;
  status: 200;
};

export type userControllerGetProfileResponseSuccess =
  userControllerGetProfileResponse200 & {
    headers: Headers;
  };
export type userControllerGetProfileResponse =
  userControllerGetProfileResponseSuccess;

export const getUserControllerGetProfileUrl = () => {
  return `/api/v1/users/profile`;
};

export const userControllerGetProfile = async (
  options?: RequestInit
): Promise<userControllerGetProfileResponse> => {
  const res = await fetch(getUserControllerGetProfileUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: userControllerGetProfileResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as userControllerGetProfileResponse;
};

export const getUserControllerGetProfileQueryKey = () => {
  return [`/api/v1/users/profile`] as const;
};

export const getUserControllerGetProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerGetProfile>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof userControllerGetProfile>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUserControllerGetProfileQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof userControllerGetProfile>>
  > = ({ signal }) => userControllerGetProfile({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerGetProfile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserControllerGetProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetProfile>>
>;
export type UserControllerGetProfileQueryError = unknown;

export function useUserControllerGetProfile<
  TData = Awaited<ReturnType<typeof userControllerGetProfile>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof userControllerGetProfile>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetProfile>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUserControllerGetProfile<
  TData = Awaited<ReturnType<typeof userControllerGetProfile>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof userControllerGetProfile>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetProfile>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUserControllerGetProfile<
  TData = Awaited<ReturnType<typeof userControllerGetProfile>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof userControllerGetProfile>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUserControllerGetProfile<
  TData = Awaited<ReturnType<typeof userControllerGetProfile>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof userControllerGetProfile>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUserControllerGetProfileQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type userControllerGetCurrentUserResponse200 = {
  data: void;
  status: 200;
};

export type userControllerGetCurrentUserResponseSuccess =
  userControllerGetCurrentUserResponse200 & {
    headers: Headers;
  };
export type userControllerGetCurrentUserResponse =
  userControllerGetCurrentUserResponseSuccess;

export const getUserControllerGetCurrentUserUrl = () => {
  return `/api/v1/users/me`;
};

export const userControllerGetCurrentUser = async (
  options?: RequestInit
): Promise<userControllerGetCurrentUserResponse> => {
  const res = await fetch(getUserControllerGetCurrentUserUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: userControllerGetCurrentUserResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as userControllerGetCurrentUserResponse;
};

export const getUserControllerGetCurrentUserQueryKey = () => {
  return [`/api/v1/users/me`] as const;
};

export const getUserControllerGetCurrentUserQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerGetCurrentUser>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof userControllerGetCurrentUser>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUserControllerGetCurrentUserQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof userControllerGetCurrentUser>>
  > = ({ signal }) => userControllerGetCurrentUser({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerGetCurrentUser>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserControllerGetCurrentUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetCurrentUser>>
>;
export type UserControllerGetCurrentUserQueryError = unknown;

export function useUserControllerGetCurrentUser<
  TData = Awaited<ReturnType<typeof userControllerGetCurrentUser>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof userControllerGetCurrentUser>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetCurrentUser>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUserControllerGetCurrentUser<
  TData = Awaited<ReturnType<typeof userControllerGetCurrentUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof userControllerGetCurrentUser>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetCurrentUser>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUserControllerGetCurrentUser<
  TData = Awaited<ReturnType<typeof userControllerGetCurrentUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof userControllerGetCurrentUser>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useUserControllerGetCurrentUser<
  TData = Awaited<ReturnType<typeof userControllerGetCurrentUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof userControllerGetCurrentUser>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUserControllerGetCurrentUserQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
