/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  HealthControllerDetails200,
  HealthControllerDetails503,
  HealthControllerReady200,
  HealthControllerReady503,
} from '.././model';

export type healthControllerLiveResponse200 = {
  data: void;
  status: 200;
};

export type healthControllerLiveResponseSuccess =
  healthControllerLiveResponse200 & {
    headers: Headers;
  };
export type healthControllerLiveResponse = healthControllerLiveResponseSuccess;

export const getHealthControllerLiveUrl = () => {
  return `/api/v1/health/live`;
};

export const healthControllerLive = async (
  options?: RequestInit
): Promise<healthControllerLiveResponse> => {
  const res = await fetch(getHealthControllerLiveUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthControllerLiveResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as healthControllerLiveResponse;
};

export const getHealthControllerLiveQueryKey = () => {
  return [`/api/v1/health/live`] as const;
};

export const getHealthControllerLiveQueryOptions = <
  TData = Awaited<ReturnType<typeof healthControllerLive>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof healthControllerLive>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthControllerLiveQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof healthControllerLive>>
  > = ({ signal }) => healthControllerLive({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthControllerLive>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HealthControllerLiveQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthControllerLive>>
>;
export type HealthControllerLiveQueryError = unknown;

export function useHealthControllerLive<
  TData = Awaited<ReturnType<typeof healthControllerLive>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthControllerLive>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerLive>>,
          TError,
          Awaited<ReturnType<typeof healthControllerLive>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthControllerLive<
  TData = Awaited<ReturnType<typeof healthControllerLive>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthControllerLive>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerLive>>,
          TError,
          Awaited<ReturnType<typeof healthControllerLive>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthControllerLive<
  TData = Awaited<ReturnType<typeof healthControllerLive>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthControllerLive>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useHealthControllerLive<
  TData = Awaited<ReturnType<typeof healthControllerLive>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthControllerLive>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getHealthControllerLiveQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type healthControllerReadyResponse200 = {
  data: HealthControllerReady200;
  status: 200;
};

export type healthControllerReadyResponse503 = {
  data: HealthControllerReady503;
  status: 503;
};

export type healthControllerReadyResponseSuccess =
  healthControllerReadyResponse200 & {
    headers: Headers;
  };
export type healthControllerReadyResponseError =
  healthControllerReadyResponse503 & {
    headers: Headers;
  };

export type healthControllerReadyResponse =
  | healthControllerReadyResponseSuccess
  | healthControllerReadyResponseError;

export const getHealthControllerReadyUrl = () => {
  return `/api/v1/health/ready`;
};

export const healthControllerReady = async (
  options?: RequestInit
): Promise<healthControllerReadyResponse> => {
  const res = await fetch(getHealthControllerReadyUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthControllerReadyResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as healthControllerReadyResponse;
};

export const getHealthControllerReadyQueryKey = () => {
  return [`/api/v1/health/ready`] as const;
};

export const getHealthControllerReadyQueryOptions = <
  TData = Awaited<ReturnType<typeof healthControllerReady>>,
  TError = HealthControllerReady503,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof healthControllerReady>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthControllerReadyQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof healthControllerReady>>
  > = ({ signal }) => healthControllerReady({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthControllerReady>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HealthControllerReadyQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthControllerReady>>
>;
export type HealthControllerReadyQueryError = HealthControllerReady503;

export function useHealthControllerReady<
  TData = Awaited<ReturnType<typeof healthControllerReady>>,
  TError = HealthControllerReady503,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthControllerReady>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerReady>>,
          TError,
          Awaited<ReturnType<typeof healthControllerReady>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthControllerReady<
  TData = Awaited<ReturnType<typeof healthControllerReady>>,
  TError = HealthControllerReady503,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthControllerReady>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerReady>>,
          TError,
          Awaited<ReturnType<typeof healthControllerReady>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthControllerReady<
  TData = Awaited<ReturnType<typeof healthControllerReady>>,
  TError = HealthControllerReady503,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthControllerReady>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useHealthControllerReady<
  TData = Awaited<ReturnType<typeof healthControllerReady>>,
  TError = HealthControllerReady503,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthControllerReady>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getHealthControllerReadyQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type healthControllerDetailsResponse200 = {
  data: HealthControllerDetails200;
  status: 200;
};

export type healthControllerDetailsResponse503 = {
  data: HealthControllerDetails503;
  status: 503;
};

export type healthControllerDetailsResponseSuccess =
  healthControllerDetailsResponse200 & {
    headers: Headers;
  };
export type healthControllerDetailsResponseError =
  healthControllerDetailsResponse503 & {
    headers: Headers;
  };

export type healthControllerDetailsResponse =
  | healthControllerDetailsResponseSuccess
  | healthControllerDetailsResponseError;

export const getHealthControllerDetailsUrl = () => {
  return `/api/v1/health/details`;
};

export const healthControllerDetails = async (
  options?: RequestInit
): Promise<healthControllerDetailsResponse> => {
  const res = await fetch(getHealthControllerDetailsUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthControllerDetailsResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as healthControllerDetailsResponse;
};

export const getHealthControllerDetailsQueryKey = () => {
  return [`/api/v1/health/details`] as const;
};

export const getHealthControllerDetailsQueryOptions = <
  TData = Awaited<ReturnType<typeof healthControllerDetails>>,
  TError = HealthControllerDetails503,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof healthControllerDetails>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getHealthControllerDetailsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof healthControllerDetails>>
  > = ({ signal }) => healthControllerDetails({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthControllerDetails>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HealthControllerDetailsQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthControllerDetails>>
>;
export type HealthControllerDetailsQueryError = HealthControllerDetails503;

export function useHealthControllerDetails<
  TData = Awaited<ReturnType<typeof healthControllerDetails>>,
  TError = HealthControllerDetails503,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthControllerDetails>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerDetails>>,
          TError,
          Awaited<ReturnType<typeof healthControllerDetails>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthControllerDetails<
  TData = Awaited<ReturnType<typeof healthControllerDetails>>,
  TError = HealthControllerDetails503,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthControllerDetails>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerDetails>>,
          TError,
          Awaited<ReturnType<typeof healthControllerDetails>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthControllerDetails<
  TData = Awaited<ReturnType<typeof healthControllerDetails>>,
  TError = HealthControllerDetails503,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthControllerDetails>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useHealthControllerDetails<
  TData = Awaited<ReturnType<typeof healthControllerDetails>>,
  TError = HealthControllerDetails503,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof healthControllerDetails>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getHealthControllerDetailsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
