/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * AMS API
 * AMS API documentation
 * OpenAPI spec version: 1.0
 */
import type { HealthControllerDetails503Details } from './healthControllerDetails503Details';
import type { HealthControllerDetails503Error } from './healthControllerDetails503Error';
import type { HealthControllerDetails503Info } from './healthControllerDetails503Info';

export type HealthControllerDetails503 = {
  status?: string;
  /** @nullable */
  info?: HealthControllerDetails503Info;
  /** @nullable */
  error?: HealthControllerDetails503Error;
  details?: HealthControllerDetails503Details;
};
